package com.oexil.staffid.enums;

public enum EmailType {
    USER_VERIFY_EMAIL,
    USER_VERIFIED_EMAIL,
    FORGET_PASSWORD_REQUEST_EMAIL,
    PAYMENT_COMPLETED,
    PAYMENT_RECEIVED,
    TWO_FACTOR_AUTH,
    USER_UPDATED,
    STUDENT_WELCOME,
    INSTRUCTOR_WELCOME,
    AGENT_WELCOME
}
